# Generated by Django 3.2.12 on 2022-02-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.BigAutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100)),
                ('EmailId', models.CharField(max_length=100)),
                ('MobileNumber', models.CharField(max_length=15)),
                ('IsProjectStarted', models.BooleanField()),
                ('Description', models.TextField()),
                ('Status', models.CharField(max_length=100)),
                ('CreatedOn', models.DateField()),
                ('UpdatedOn', models.DateField()),
                ('Technologies', models.ManyToManyField(to='base.Technology')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
