# Generated by Django 3.2.12 on 2022-02-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220228_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechnologyId', models.ForeignKey(db_column='Tech_Id', on_delete=django.db.models.deletion.CASCADE, related_name='Tech_Id', to='base.technology')),
                ('TechnologyName', models.ForeignKey(db_column='Tech_Name', on_delete=django.db.models.deletion.CASCADE, related_name='Tech_Name', to='base.technology')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
    ]
