# Generated by Django 3.2.12 on 2022-02-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customertechnology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customertechnology',
            old_name='UserName',
            new_name='CustomerName',
        ),
        migrations.AlterField(
            model_name='customertechnology',
            name='TechnologyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Technology_Id', to='base.technology'),
        ),
        migrations.AlterField(
            model_name='customertechnology',
            name='TechnologyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Technology_Name', to='base.technology'),
        ),
    ]
