# Generated by Django 3.2.12 on 2022-02-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220228_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerTechnology',
        ),
    ]
