# Generated by Django 3.2.12 on 2022-03-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220315_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='UpdatedOn',
            field=models.DateField(auto_now=True),
        ),
    ]
