# Generated by Django 3.2.12 on 2022-03-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_customer_updatedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='IsProjectStarted',
            field=models.BooleanField(default='1'),
        ),
    ]
